# Generated by Django 5.1.4 on 2025-02-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subject',
            new_name='subjects',
        ),
    ]
