# Generated by Django 5.1.4 on 2025-02-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0002_rename_subject_exam_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subjects',
            new_name='subject',
        ),
    ]
