# Generated by Django 5.1.4 on 2025-03-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0003_rename_subjects_exam_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_type',
            new_name='paper_type',
        ),
    ]
