# Generated by Django 5.1.4 on 2025-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0005_remove_questionoption_question_exam_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
