# Generated by Django 5.1.4 on 2025-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0007_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('fib', 'Fill in the Blanks'), ('essay', 'Essay')], max_length=50),
        ),
    ]
