# Generated by Django 5.1.4 on 2025-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('FIB', 'Fill in the Blanks'), ('essay', 'Essay')], max_length=50),
        ),
    ]
