# Generated by Django 5.1.4 on 2025-03-17 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0010_alter_examresult_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams_management.examresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_management.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams_management.questionoption')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
