# Generated by Django 5.1.4 on 2025-05-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0012_examresult_last_activity_alter_examresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_to_answer',
            field=models.PositiveIntegerField(default=0, help_text='How many questions a student should answer.'),
        ),
    ]
