# Generated by Django 5.1.4 on 2025-05-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0013_exam_questions_to_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='questions_to_answer',
            new_name='student_question_limit',
        ),
    ]
