# Generated by Django 5.1.4 on 2025-05-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0014_rename_questions_to_answer_exam_student_question_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams_management.question'),
        ),
    ]
