# Generated by Django 5.1.4 on 2025-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0015_examresult_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='questions',
        ),
        migrations.AddField(
            model_name='examresult',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exams_management.question'),
        ),
    ]
