# Generated by Django 5.1.4 on 2025-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0016_remove_examresult_questions_examresult_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='highest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
