# Generated by Django 5.1.4 on 2025-08-08 16:55

import os
import re
import json
from django.db import migrations
from datetime import timedelta

def load_exams(apps, schema_editor):
    Grade = apps.get_model('school_management', 'Grade')
    Subject = apps.get_model('school_management', 'Subject')
    Folder = apps.get_model('exams_management', 'Folder')
    Question = apps.get_model('exams_management', 'Question')
    QuestionOption = apps.get_model('exams_management', 'QuestionOption')
    Exam = apps.get_model('exams_management', 'Exam')
    ExamBoard = apps.get_model('exams_management', 'ExamBoard')

    ss3qna_folder = os.path.join(os.path.dirname(__file__), 'ss3qna')
    if not os.path.exists(ss3qna_folder):
        print(f"Folder {ss3qna_folder} not found.")
        return

    folder, _ = Folder.objects.get_or_create(
        name="Senior Secondary",
        defaults={'description': 'Senior Secondary Past Questions'}
    )

    for filename in os.listdir(ss3qna_folder):
        if not filename.endswith('.json'):
            continue
        
        file_path = os.path.join(ss3qna_folder, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            try:
                raw_data = json.load(file)
                questions_data = raw_data.get("questions", [])
            except Exception as e:
                print(f"Error loading {filename}: {e}")
                continue

            subject_name = filename.replace('.json', '').replace('_', ' ').title()
            subject = Subject.objects.filter(name__icontains=subject_name).first()
            if not subject:
                print(f"Subject {subject_name} not found.")
                continue

            exam_questions = []

            for qdata in questions_data:
                # Extract year and board
                exam_year_match = re.search(r"\d{4}", qdata.get('exam_year', ''))
                exam_board_match = re.search(r"[A-Z]+", qdata.get('exam_year', ''))
                exam_year = int(exam_year_match.group(0)) if exam_year_match else None
                exam_board_abbr = exam_board_match.group(0) if exam_board_match else "WAEC"

                exam_board = ExamBoard.objects.filter(abbreviation__iexact=exam_board_abbr).first()
                question_type = 'multiple_choice' if qdata.get('options') else 'essay'
                # question_type = 'essay' if not qdata.get('options') or qdata.get('answer').lower() == 'd' else 'multiple_choice'
                
                q = Question.objects.create(
                    question_text=qdata['question_text'],
                    question_type=question_type,
                    exam_board=exam_board,
                    exam_year=exam_year,
                    marks=qdata.get('marks', 1),
                    media=qdata.get('media'),
                )

                for key, text in qdata.get('options', {}).items():
                    QuestionOption.objects.create(
                        question=q,
                        option_text=text,
                        is_correct=(key.upper() == qdata['answer'].upper())
                    )

                exam_questions.append(q)

            exam = Exam.objects.create(
                folder=folder,
                title=f"{subject_name} Past Questions",
                subject=subject,
                paper_type='practice',
                grade_level=Grade.objects.get(name='SSS 3'),
                duration=timedelta(minutes=15),
                instructions='Answer all questions.',
            )

            exam.questions.set(exam_questions)
            print(f"Loaded {len(exam_questions)} questions for subject {subject_name}")

def populate_exam_boards(apps, schema_editor):
    ExamBoard = apps.get_model("exams_management", "ExamBoard")
    defaults = [
        ("WAEC", "West African Examinations Council", "Nigeria / West Africa"),
        ("JAMB", "Joint Admissions and Matriculation Board", "Nigeria"),
        ("NECO", "National Examinations Council", "Nigeria"),
        ("BECE", "Basic Education Certificate Exam", "Ghana / Nigeria"),
        ("SAT", "Scholastic Assessment Test", "USA"),
    ]
    for abbr, name, country in defaults:
        ExamBoard.objects.get_or_create(abbreviation=abbr, defaults={"name": name, "country": country})


class Migration(migrations.Migration):

    dependencies = [
        ('exams_management', '0018_examboard_question_exam_year_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_exam_boards),
        migrations.RunPython(load_exams),
    ]
