# Generated by Django 5.1.4 on 2025-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='children',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='core.parentprofile'),
        ),
    ]
