# Generated by Django 5.1.4 on 2025-01-09 00:35

from django.db import migrations

def create_defaults(apps, schema_editor):
    Grade = apps.get_model('school_management', 'Grade')  
    Subject = apps.get_model('school_management', 'Subject')  
    default_grades = [
        'JSS 1', 'JSS 2', 'JSS 3', 'SSS 1', 'SSS 2', 'SSS 3'
    ]
    default_subjects = [
        "Mathematics",
        "English Language",
        "Physics",
        "Chemistry",
        "Biology",
        "Further Mathematics",
        "Agricultural Science",
        "Economics",
        "Geography",
        "Government",
        "History",
        "Literature in English",
        "Christian Religious Studies (CRS)",
        "Islamic Religious Studies (IRS)",
        "Civic Education",
        "Social Studies",
        "Computer Studies",
        "Physical and Health Education (PHE)",
        "Technical Drawing",
        "Fine Arts",
        "Music",
        "French",
        "Yoruba",
        "Hausa",
        "Igbo",
        "Home Economics",
        "Commerce",
        "Accounting",
        "Financial Accounting",
        "Bookkeeping",
        "Typewriting",
        "Shorthand",
        "Basic Science",
        "Basic Electricity",
        "Basic Electronics",
        "Home Management",
        "Store Management",
        "Office Practice",
        "Insurance",
        "Fabrication & Welding",
        "Electrical Installation",
        "Marketing",
        "Basic Technology",
        "Integrated Science",
        "Business Studies",
        "Cultural and Creative Arts (CCA)",
        "Arabic Studies",
        "Food and Nutrition",
        "Clothing and Textiles",
        "Woodwork",
        "Metalwork",
        "Auto Mechanics",
        "Electronics",
        "Building Construction",
        "Fisheries",
        "Animal Husbandry",
        "Health Education",
        "Physical Education",
        "Drama",
        "Dance",
        "Photography",
        "Entrepreneurship",
        "Information and Communication Technology (ICT)",
        "Data Processing",
        "Visual Arts",
        "Applied Electricity",
        "Technical Education",
        "General Mathematics",
        "General Science",
        "Environmental Science",
        "Security Education",
        "National Values Education",
        "Religious and Moral Education",
        
    ]
    
    for grade_name in default_grades:
        Grade.objects.get_or_create(name=grade_name)
    
    for subject_name in default_subjects:
        Subject.objects.get_or_create(name=subject_name)

class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_defaults),
    ]
