# Generated by Django 5.1.4 on 2025-05-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_grade_level_fke_and_more'),
        ('school_management', '0002_populate_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.grade'),
        ),
    ]
