# Generated by Django 5.1.4 on 2025-05-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fke'),
        ('school_management', '0002_populate_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade_level_fke',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level_changed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.grade'),
        ),
    ]
