# Generated by Django 5.1.4 on 2025-05-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_studentprofile_grade_level_fke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade_level_changed',
        ),
    ]
